import Head from "next/head";
import {
  AiFillMail,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className= {darkMode ? "dark" : ""}>
      <header>
    <nav class="bg-black border-black px-4 lg:px-6 py-2.5 dark:bg-white">
        <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
            <a href="" class="flex items-center">
                
                <span id = "home" class="text-white self-center text-xl font-burtons whitespace-nowrap dark:text-black">Portofolio</span>
            </a>
            <div class="flex items-center lg:order-2">
    
              
            </div>
            <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-0 " id="mobile-menu-2 ">
                <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-24 lg:mt-0 ">
                    <li>
                        <a href="#home" class="block py-2 pr-4 pl-3 text-white rounded bg-primary-700 lg:bg-transparent lg:text-white lg:p-0 dark:text-black lg:hover:text-transparent lg:dark:hover:bg-transparent " aria-current="page">Home</a>
                    </li>
                    <li>
                        <a href= "#skills" class="block py-2 pr-4 pl-3 text-white border-b border-gray-100 hover:bg-transparent lg:hover:bg-transparent lg:border-0 lg:hover:text-transparent lg:p-0 dark:text-black lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">Skills</a>
                    </li>
                    <li>
                        <a href="#projects" class="block py-2 pr-4 pl-3 text-white border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-transparent lg:p-0 dark:text-black lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">Projects</a>
                    </li>
                    <li>
                        <a href="#exp" class="block py-2 pr-4 pl-3 text-white border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-transparent lg:p-0 dark:text-black lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">Experience</a>
                    </li>
                    <li>
                        <a href="#contact" class="block py-2 pr-4 pl-3 text-white border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-transparent lg:p-0 dark:text-black lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
      <Head>
        <title>Personal Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-3xl"></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-400 text- to-cyan-700 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:8938a88e-0929-38f2-bd46-44ba5ebb3029"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 id = "Me" className="text-5xl py-2 text-blue-500 font-medium dark:text-cyan-400 md:text-6xl">
              Malek Abouelkhair
            </h2>
            <h3 className="text-2xl py-3 dark:text-white md:text-3xl">
              Software Developer and Electrical Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            As an upcoming engineer, I strive to be a source of infectious energy and enthusiasm, quickly impressing
potential employers with my technical skills, attention to detail, and strong work ethic. I am always eager to learn
and stay up to date with the latest developments in the industry. My passion for my work is evident in everything
I do, from brainstorming new ideas to working late to meet project deadlines. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="mailto:malekgamal16@gmail.com">
              <AiFillMail />
            </a>
            <a href="https://www.linkedin.com/in/malek-abouelkhair-445641245/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Meko6701">
              <AiFillGithub />
            </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 id = "skills" className="font-burtons text-5xl py-3 dark:text-white ">Skills</h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="bg-gradient-to-r from-cyan-400 text- to-cyan-700 text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-3xl font-burtons pt-8 pb-2  ">
                Hardware
              </h3>
              <p className="py-6">
              Experience gained through courses studied at university such as intro to Electrical Engineering, Logic Deisgn, Microprocessor System Project.
              </p>
              <h4 className="py-1 text-white">Electronic Devices</h4>
              <p className="text-white py-1">Circuits</p>
              <p className="text-white py-1">Microprocessers</p>
              <p className="text-white py-1">Logic Design</p>
              <p className="text-white py-1">Semiconductor Devices</p>
            </div>
            <div className="bg-gradient-to-r from-cyan-400 text- to-cyan-700 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-3xl font-burtons pt-8 pb-2 ">
                Programming
              </h3>
              <p className="py-6">
                Have great experience with various frameworks and libraries such as React, Tkinter, OpenCV, and Tailwind.
              </p>
              <h4 className="py-1 text-white">JavaScript</h4>
              <p className="text-white py-1">C/C++</p>
              <p className="text-white py-1">Python</p>
              <p className="text-white py-1">HTML & CSS</p>
              <p className="text-white py-1">MatLab</p>
            </div>
            <div className="bg-gradient-to-r from-cyan-400  to-cyan-700 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-3xl font-burtons pt-8 pb-2 ">Communication</h3>
              <p className="py-6">
                Through previous experience as a Managnent intern and Sponsor executive.
              </p>
              <h4 className="py-1 text-white">Performance Feedback</h4>
              <p className="text-white py-1">Presentation Skills</p>
              <p className="text-white py-1">Time Managment</p>
              <p className="text-white py-1">Adaptability</p>
              <p className="text-white py-1">Networking</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 id = "projects" className="font-burtons text-5xl py-1 dark:text-white ">Projects</h3>
           
            
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap hover:Image-transparent lg:hover:Image-transparent lg:hover:Image-transparent">
            <div className="basis-1/3 flex-1 ">
            <a href="https://github.com/Meko6701/CogniSign.git">
              <Image
                className="rounded-lg object-cover div-img"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                
              />
            </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Meko6701/Gui-Development">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Meko6701/CogniSign.git">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />   
              
            </div>
          </div>
        </section>
        <section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
      <div class="mx-auto max-w-screen-sm text-center lg:mb-16 mb-8">
          <h2 id ="exp" class="mb-4 text-3xl lg:text-5xl tracking-tight font-burtons text-gray-900 dark:text-white">Experience</h2>
          
      </div> 
      <div class="grid gap-36 lg:grid-cols-1 ">
          <article class="p-6 bg-gradient-to-r from-cyan-400 text- to-cyan-700 rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 ">
              <div class="flex justify-between items-center mb-5 text-white">
                  <span class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
                      <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z"></path></svg>
                      Club
                  </span>
                  <span class="text-sm">Present</span>
              </div>
              <h2 class="mb-2 text-2xl font-bold tracking-tight text-white dark:text-white"><a href="#">Sponsorship Executive at DeltaHacks</a></h2>
              <p class="mb-5 font-light text-black dark:text-black">Responsible for identifying and securing financial support from external organizations, coordinating partnerships, and managing relationships with sponsors to ensure the successful execution of hackathon events.</p>
              <div class="flex justify-between items-center">
                  <div class="flex items-center space-x-4">
                      <img class="w-35 h-35 rounded-full" src="https://media.licdn.com/dms/image/C4E0BAQEbmaGyiF61Nw/company-logo_200_200/0/1629406343465?e=1701302400&v=beta&t=ZQmC23bOolHsd9ZIsUMl8khkoJnv_Bx9hXWbK8gxOJw" />
                      
                  </div>
                  
              </div>
          </article> 
          <article class="p-6 bg-gradient-to-r from-cyan-400 text- to-cyan-700 rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
              <div class="flex justify-between items-center mb-5 text-white">
                  <span class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
                      <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z" clip-rule="evenodd"></path><path d="M15 7h1a2 2 0 012 2v5.5a1.5 1.5 0 01-3 0V7z"></path></svg>
                      Internship 
                  </span>
                  <span class="text-sm">1 year ago</span>
              </div>
              <h2 class="mb-2 text-2xl font-bold tracking-tight text-white dark:text-white"><a href="#">Managment Intern at Al Shaqab Racing</a></h2>
              <strong class="mb-5 font-light text-black dark:text-black font-weight:bold">Helping in communicating purchases to suppliers, setting up charts and tables to fill in with information about customers, and horses entered in race events. Making sure equipment for horse race events was purchased and rearranged for their purposes.</strong>
              <div class="flex justify-between items-center center">
                  <div class="flex items-center space-x-4 center">
                      <img class="w-48 h-48 rounded-full flex-center items-center center" src="https://upload.wikimedia.org/wikipedia/commons/5/58/Alshaqablogo.png" />
                      
                  </div>

              </div>
          </article>                  
      </div>  
  </div>
</section>
        
        
        <section className="contact py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-lg mx-auto text-center mb-16">
              <h2 id = "contact" className="text-5xl font-burtons mb-6 dark:text-white">Contact Me</h2>
              <p className="text-gray-600 dark:text-gray-400 ">
                Fill in the form below to get in touch with me.
              </p>
            </div>
            <form
              action="malekgamal16@gmail.com"
              method="POST"
              className="max-w-lg mx-auto"
            >
              <div className="mb-6">
                <input
                  type="text"
                  name="name"
                  placeholder="Your Name"
                  className="w-full px-4 py-3 rounded-lg border"
                  required
                />
              </div>
              <div className="mb-6">
                <input
                  type="email"
                  name="email"
                  placeholder="Your Email"
                  className="w-full px-4 py-3 rounded-lg border"
                  required
                />
              </div>
              <div className="mb-6">
                <textarea
                  name="message"
                  rows="5"
                  placeholder="Your Message"
                  className="w-full px-4 py-3 rounded-lg border"
                  required
                ></textarea>
              </div>
              <div className="text-center">
             
              
                <button
                  type="submit"
                  className="bg-cyan-600 text-white px-6 py-3 rounded-lg"
                >
                  Send Message
                </button>
              
                
              </div>
            </form>
          </div>
        </section>
      </main>

    
    </div>
    
  );
}

